# Generated by Django 4.0.1 on 2022-01-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.DateTimeField(auto_now_add=True)),
                ('value', models.UUIDField()),
            ],
        ),
    ]
