# Generated by Django 4.0.1 on 2022-01-14 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
